services:
  keycloak-airport:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-airport
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
    volumes:
      - ./import:/opt/keycloak/data/import
    command: >
      start-dev
      --hostname=localhost
      --import-realm

#To apply new configuration changes from keycloak admin page
# sudo docker exec -it keycloak-airport \
# /opt/keycloak/bin/kc.sh export \
# --dir /opt/keycloak/data/import \
# --realm airport